apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    name: adminer
    app: ecm-smart-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    name: adminer
    app: ecm-smart-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: ecm-smart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: adminer
      app: ecm-smart-service
  template:
    metadata:
      name: adminer
      labels:
        name: adminer
        app: ecm-smart-service

    spec:
      containers:
      - name: adminer
        image: adminer
        imagePullPolicy: IfNotPresent        
            
        ports:
        - containerPort: 8080