apiVersion: v1
kind: Service
metadata:
  name: ecm-filenet-service
  labels:
    name: ecm-filenet-service
    app: ecm-smart-service
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: ecm-filenet-service
    app: ecm-smart-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm-filenet-service
  labels:
    app: ecm-smart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ecm-filenet-service
      app: ecm-smart-service
  template:
    metadata:
      name: ecm-filenet-service
      labels:
        name: ecm-filenet-service
        app: ecm-smart-service

    spec:
      containers:
      - name: ecm-filenet-service
        image: ecm-filenet-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081