apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    name: mysql-server
    app: ecm-smart-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-server
    app: ecm-smart-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: ecm-smart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-server
      app: ecm-smart-service
  template:
    metadata:
      name: mysql-server
      labels:
        name: mysql-server
        app: ecm-smart-service

    spec:
      containers:
      - name: mysql-server
        image: mysql/mysql-server:latest
        imagePullPolicy: IfNotPresent
        env:      
          - name: MYSQL_DATABASE
            value: db
          - name: MYSQL_USER
            value: ecm
          - name: MYSQL_PASSWORD
            value: ecm@123
          - name: MYSQL_ROOT_PASSWORD
            value: root
            
        ports:
        - containerPort: 3306    