apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    name: mysql-server
    app: ecm-smart-service
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-server
    app: ecm-smart-service

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/mysql_data
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: ecm-smart-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: ecm-smart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-server
      app: ecm-smart-service
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysql-server
      labels:
        name: mysql-server
        app: ecm-smart-service

    spec:
      containers:
      - name: mysql-server
        image: mysql:5.6
        imagePullPolicy: IfNotPresent            
        env:      
          - name: MYSQL_DATABASE
            value: authDB                     
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: mysqlusername
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: mysqlpassword
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: rootpassword    
            
        ports:
        - containerPort: 3306
        
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
            
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc