apiVersion: v1
kind: Service
metadata:
  name: track-mysql
  labels:
    app: track
spec:
  ports:
    - port: 3306
  selector:
    app: track
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/mysql_data
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: track
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: track-mysql
  labels:
    app: track
spec:
  selector:
    matchLabels:
      app: track
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: track
    spec:
      containers:
      - image: mysql:5.6
      #- image: mysql/mysql-server:latest
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: track
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc