apiVersion: v1
kind: Service
metadata:
  name: ecm-gateway-service
  labels:
    name: ecm-gateway-service
    app: ecm-smart-service
spec:  
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: ecm-gateway-service
    app: ecm-smart-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecm-gateway-service
  labels:
    app: ecm-smart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ecm-gateway-service
      app: ecm-smart-service
  template:
    metadata:
      name: ecm-gateway-service
      labels:
        name: ecm-gateway-service
        app: ecm-smart-service
    spec:
      containers:
      - name: ecm-gateway-service
        image: ecm-gateway-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080