apiVersion: v1
kind: Service
metadata:
  name: ecm-gateway-service
  labels:
    name: ecm-gateway-service
    app: ecm-smart-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: ecm-gateway-service
    app: ecm-smart-service
