apiVersion: v1
kind: Service
metadata:
  name: ecm-filenet-service
  labels:
    name: ecm-filenet-service
    app: ecm-smart-service
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    name: ecm-filenet-service-pod
    app: ecm-smart-service
