apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server-deployment
  labels:
    app: ecm-smart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-server-pod
      app: ecm-smart-service
  template:
    metadata:
      name: mysql-server-pod
      labels:
        name: mysql-server-pod
        app: ecm-smart-service

    spec:
      containers:
      - name: mysql-server
        image: mysql/mysql-server:latest
        imagePullPolicy: IfNotPresent
        env:      
          - name: MYSQL_DATABASE
            value: db
          - name: MYSQL_USER
            value: ecm
          - name: MYSQL_PASSWORD
            value: ecm@123
          - name: MYSQL_ROOT_PASSWORD
            value: root
            
        ports:
        - containerPort: 3306